version: '3.9'
volumes:
  html:
services:
  db:
    image: mysql:8.0
    volumes:
      - ./db/dump:/docker-entrypoint-initdb.d
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: somewordpress
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
  wp-php:
    depends_on:
      - db
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    restart: always
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_NAME: wordpress
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
      WP_DEBUG: 1
      WP_DEBUG_DISPLAY: 0
    volumes:
      - html:/var/www/html/wp
      - ../miles-wp-theme/:/var/www/html/wp/wp-content/themes/miles-wp-theme
      - ../miles-wp-web-components-plugin/:/var/www/html/wp/wp-content/plugins/miles-wp-web-components-plugin/
      - ./paid-plugins:/var/www/html/paid-plugins
      - ./composer.json:/var/www/html/composer.json
      - ./wp-config/wp-config.php:/var/www/html/wp-config.php
  nginx:
    image: nginx
    ports:
      - "8880:80"
    volumes:
      - html:/var/www/html/wp
      - ../miles-wp-theme/:/var/www/html/wp/wp-content/themes/miles-wp-theme
      - ../miles-wp-web-components-plugin/:/var/www/html/wp/wp-content/plugins/miles-wp-web-components-plugin/
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    links:
      - wp-php
  wp-cli:
    container_name: wp-cli
    depends_on:
      - wp-php
      - db
    image: wordpress:cli
    command: tail -f /dev/null
    volumes:
      - html:/var/www/html/wp
      - ./wp-config/wp-config.php:/var/www/html/wp-config.php
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_NAME: wordpress
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
