name: Deploy web components to WP Hosting

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: true
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"
          cache-dependency-path: ./miles_web_components/package-lock.json
      - name: Install dependencies and build
        run: |
          cd miles_web_components
          npm install
          npm run build --if-present
      - name: Upload with SFTP
        uses: Creepios/sftp-action@v1.0.3
        with:
          host: ${{ secrets.SFTP_HOST }}
          port: 22
          username: ${{ secrets.SFTP_USERNAME }}
          passphrase: ${{ secrets.SFTP_PASSPHRASE }}
          privateKey: ${{ secrets.SFTP_PRIVATE_KEY }}
          localPath: ./miles_web_components/public
          remotePath: ./wp-newsite/wp-content/plugins/miles-wp-web-components-plugin/miles-wc-new
