name: Deploy WP theme to WP Hosting

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: true
      - name: Upload with SFTP
        uses: Creepios/sftp-action@v1.0.3
        with:
          host: ${{ secrets.SFTP_HOST }}
          port: 22
          username: ${{ secrets.SFTP_USERNAME }}
          passphrase: ${{ secrets.SFTP_PASSPHRASE }}
          privateKey: ${{ secrets.SFTP_PRIVATE_KEY }}
          localPath: ./miles-wp-theme
          remotePath: ./wp-newsite/wp-content/themes/miles-wp-theme # Path to theme folder on WP Hosting
