name: Deploy WP theme to WP Hosting

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # OR "2" -> To retrieve the preceding commit.
          submodules: true
      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v39
        with:
          path: ./miles-wp-theme
      # NOTE: `since_last_remote_commit: true` is implied by default and falls back to the previous local commit.
      - name: Move all changed files to a directory
        run: |
          mkdir changed-files
          cp ./miles-wp-themes/${{ steps.changed-files.outputs.all_changed_files }} changed-files --parents
          ls changed-files -R
      # - name: Upload with SFTP
      #   uses: Creepios/sftp-action@v1.0.3
      #   with:
      #     host: ${{ secrets.SFTP_HOST }}
      #     port: 22
      #     username: ${{ secrets.SFTP_USERNAME }}
      #     passphrase: ${{ secrets.SFTP_PASSPHRASE }}
      #     privateKey: ${{ secrets.SFTP_PRIVATE_KEY }}
      #     localPath: ./changed-files/miles-wp-theme
      #     remotePath: ./wp-newsite/wp-content/themes/miles-wp-theme # Path to theme folder on WP Hosting