name: Upload files to WP Hosting with SFTP

on:
  workflow_call:
    inputs:
      localPath:
        required: true
        type: string
      remotePath:
        required: true
        type: string
    secrets: inherit

jobs:
  publish:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
    steps:
      - name: Upload with SFTP
        uses: Creepios/sftp-action@v1.0.3
        with:
          host: ${{ secrets.SFTP_HOST }}
          port: 22
          username: ${{ secrets.SFTP_USERNAME }}
          passphrase: ${{ secrets.SFTP_PASSPHRASE }}
          privateKey: ${{ secrets.SFTP_PRIVATE_KEY }}
          localPath: ${{ inputs.localPath }}
          remotePath: ${{ inputs.remotePath }}
